version: '3.1'

services:

  postgres:
    container_name: postgres
    image: postgres:9.6.20
    restart: unless-stopped
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
       - ../docker_data/grg:/var/lib/postgresql/data
       - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.30
    environment:
      PGADMIN_DEFAULT_EMAIL: "twl@phase-ii.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    volumes:
       - ../docker_data/.pgadmin:/root/.pgadmin
       - ../docker_data/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge