version: '3.1'

services:

  rabbit:
    container_name: grg-rabbit
    image: rabbitmq:3.8-management-alpine
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ../docker_data/grg/rabbitmq/data/:/var/lib/rabbitmq/
      - ../docker_data/grg/rabbitmq/logs/:/var/log/rabbitmq/
      # may be needed to set 777 to rabbitmq folder
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    #user: rabbitmq
    networks:
      - grg-network
  postgres:
    container_name: grg-postgres
    image: postgres:9.6.24
    restart: unless-stopped
    ports: 
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
       - ../docker_data/grg/postgres:/var/lib/postgresql/data
       - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - grg-network

  pgadmin:
    container_name: grg-pgadmin
    image: dpage/pgadmin4:6.4
    environment:
      PGADMIN_DEFAULT_EMAIL: "twl@phase-ii.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    volumes:
       - ../docker_data/grg/.pgadmin:/root/.pgadmin
       - ../docker_data/grg/pgadmin:/var/lib/pgadmin
    ports:
      - "5053:80"
    networks:
      - grg-network
    restart: unless-stopped

networks:
  grg-network:
    driver: bridge