export const USER_SET = "USER_SET";

export const OFFICE_CREATE = "OFFICE_CREATE";
export const OFFICES_LIST = "OFFICES_LIST";
export const OFFICES_LIST_ERROR = "OFFICES_LIST_ERROR";

export const RESOURCE_CREATE = "RESOURCE_CREATE";
export const RESOURCES_LIST = "RESOURCES_LIST";
export const RESOURCES_LIST_ERROR = "RESOURCES_LIST_ERROR";

export const ORDER_CREATE = "ORDER_CREATE";
export const ORDER_ERROR = "ORDER_ERROR";
