export const OFFICE_CREATE = "OFFICE_CREATE";
export const OFFICES_LIST = "OFFICES_LIST";
export const OFFICES_LIST_ERROR = "OFFICES_LIST_ERROR";

export const RESOURCES_LIST = "RESOURCES_LIST";
export const RESOURCES_LIST_ERROR = "RESOURCES_LIST_ERROR";
