version: "3"

services:
  rabbit:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/logs/:/var/log/rabbitmq/
      # may be needed to set 777 to rabbitmq folder
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    #user: rabbitmq
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge