CREATE USER grg_test WITH ENCRYPTED PASSWORD 'grg_test';;
CREATE DATABASE grg_test;
GRANT ALL PRIVILEGES ON DATABASE grg_test TO grg_test;

CREATE USER grg WITH ENCRYPTED PASSWORD 'grg_password';
CREATE DATABASE grg;
GRANT ALL PRIVILEGES ON DATABASE grg TO grg;